# Site settings
title: "Nohm Devices - Ultra-low-power electronics leveraging non-Ohmic transport"
email: manichandra.morampudi@gmail.com
baseurl: ""
url: "https://nohm-devices.com"

# Build settings
markdown: kramdown
exclude: []
